import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content="Home" />
        <meta
          property="og:description"
          content="Explore my portfolio where I present my development and design skills through my creative and captivating achievements."
        />
        <meta property="og:url" content="https://vittoriobusatta.fr" />
        <meta
          property="og:image"
          content="preview.svg"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
