import React from "react";
import Head from "next/head";
import fs from "fs";
import Link from "next/link";
import Image from "next/image";
import Header from "@/components/Header";

export async function getStaticProps() {
  const data = await JSON.parse(fs.readFileSync("./public/db.json", "utf-8"));
  return { props: { data } };
}

function Home({ data }) {
  console.log(data);
  data.map((item, index) => {
    console.log(item);
  });
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content="Home" />
        <meta
          property="og:description"
          content="Generated by create next app"
        />
        <meta property="og:image" content="/favicon.ico" />
        <meta property="og:url" content="https://www.example.com" />
        <meta name="theme-color" content="#fff" />
      </Head>

      <Header logoColor={"#222"} />

      <main className="home">
        {data.map((item, index) => (
          <figure className="home__items" key={item.id}>
            <Link href={`/projects/${item.id}`}>
              <figcaption>
                <span>0{index + 1}</span>
                <h1>{item.name}</h1>
              </figcaption>
              <div className="home__items__img">
                {item.thumbnail && (
                  <Image
                    src={item.thumbnail.src}
                    alt={item.thumbnail.alt}
                    width={500}
                    height={500}
                  />
                )}
              </div>
            </Link>
          </figure>
        ))}
      </main>
    </>
  );
}

export default Home;
