name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name : 🔨 Build Project
        run: |
            npm install
            npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.vittoriobusatta.fr
          username: vitto1874827
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .next/
          server-dir: /

